### ISSUE TITLE
Tutorial on how to use the UI components

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-UILibrary-Android#20]
Is there any tutorial on actually processing the events of the ui library after https://developer.dji.com/mobile-sdk/documentation/android-tutorials/UILibraryDemo.html?

For example, I click on the CameraCaptureWidget (the white circle on the right). Right now I have the CameraControlsWidget, but how do I take the picture and get the resulting picture and use it? Am I suppose to create my own onClick listener or is there an existing listener I hook into?

**Comment by DJI-RobertLiu** [comment]
We do not open such kind of event yet.  But thanks for the requirement, we will consider it.  
In your example, before we open the event callback or interfaces, you might need refer to our SDKSample code to:
 1. listen on camera SystemState to check if the picture is taking.
 2. then you need set the camera's CameraMode into PLAYBACK or MEDIA_DOWNLOAD mode to preview or download the picture.

Btw, the onClick method in the CameraCaptureWidget is public, you can override it if need, but I do not recommend this way just because the actions in the onClick event are asynchronous.
